#!/usr/bin/python3

import sys
import base64

with open(sys.argv[2]) as myfile:
    if sys.argv[1] == "encode":
        output = base64.urlsafe_b64encode(myfile.read().encode("utf-8")).decode("utf-8")
        print(output, end="")
    elif sys.argv[1] == "decode":
        output = base64.urlsafe_b64decode(myfile.read().encode("utf-8")).decode("utf-8")
        print(output, end="")
