#!/usr/bin/bash

unit_name="${1}"
systemctl is-active ${unit_name} > /dev/null

if [[ $? -eq 0 ]]; then
    echo "stopping"
    systemctl stop ${unit_name}
else
    echo "starting"
    systemctl start ${unit_name}
fi

if [[ $? -eq 0 ]]; then
    echo "success"
else
    echo "failed"
fi
sleep 1
