#!/bin/bash

if [[ $EUID -eq 0 ]]; then
    echo '     _              __'
    echo '    / `\  (~._    ./  )'
    echo '    \__/ __`-_\__/ ./'
    echo '   _ \ \/  \   \ |_   __'
    echo ' (   )  \__/ -^    \ /  \'
    echo '  \_/ "  \  | o  o  |.. /  __'
    echo "       \\. --' ====  /  || /  \\ "
    echo '         \   .  .  |---__.\__/'
    echo '         /  :     /   |   |'
    echo '         /   :   /     \_/'
    echo '      --/ ::    ('
    echo '     (  |     (  (____'
    echo '   .--  .. ----**.____)'
    echo '   \___/          '
else
    echo "It's a weird tree."
fi
